"""
One-time script: fetch Arabic + English text for all hadith refs cited in
seed-task files, write to src/data/hadith.js.

Source: fawazahmed0/hadith-api (jsdelivr CDN, no auth, no rate limits).

Usage: python scripts/fetch-hadith.py
"""
import urllib.request
import json
import re
import sys
import os
import subprocess
from concurrent.futures import ThreadPoolExecutor, as_completed

CDN = "https://cdn.jsdelivr.net/gh/fawazahmed0/hadith-api@1/editions"
SEED_DIR = os.path.join(os.path.dirname(__file__), "..", "src", "data", "seed-tasks")
OUT_FILE = os.path.join(os.path.dirname(__file__), "..", "src", "data", "hadith.js")

# Map of collection display names found in seed-tasks → fawazahmed0 edition slug
COLLECTION_MAP = {
    "Sahih Bukhari": "bukhari",
    "Sahih al-Bukhari": "bukhari",
    "Sahih Muslim": "muslim",
    "Sunan Abi Dawud": "abudawud",
    "Sunan Abu Dawud": "abudawud",
    "Sunan Ibn Majah": "ibnmajah",
    "Sunan an-Nasai": "nasai",
    "Sunan an-Nasa'i": "nasai",
    "Sunan al-Nasa'i": "nasai",
    "Sunan al-Nasai": "nasai",
    "Jami at-Tirmidhi": "tirmidhi",
    "Sunan al-Tirmidhi": "tirmidhi",
    "Muwatta Malik": "malik",
}

DISPLAY_MAP = {
    "bukhari": "Sahih al-Bukhari",
    "muslim": "Sahih Muslim",
    "abudawud": "Sunan Abi Dawud",
    "ibnmajah": "Sunan Ibn Majah",
    "nasai": "Sunan an-Nasa'i",
    "tirmidhi": "Jami at-Tirmidhi",
    "malik": "Muwatta Malik",
}

# Pattern: ### <collection name> <number>
HADITH_HEADING_RE = re.compile(r"^### ([A-Za-z][A-Za-z' -]+?)\s+(\d+)\s*$", re.MULTILINE)


def collect_refs():
    refs = set()  # (slug, number)
    skipped = set()  # raw collection names with no mapping
    for fname in os.listdir(SEED_DIR):
        if not fname.endswith(".js"):
            continue
        with open(os.path.join(SEED_DIR, fname), encoding="utf-8") as f:
            text = f.read()
        for m in HADITH_HEADING_RE.finditer(text):
            name, num = m.group(1).strip(), int(m.group(2))
            slug = COLLECTION_MAP.get(name)
            if slug:
                refs.add((slug, num))
            else:
                skipped.add(name)
    return sorted(refs), sorted(skipped)


def fetch_one(slug, number):
    url_ar = f"{CDN}/ara-{slug}/{number}.min.json"
    url_en = f"{CDN}/eng-{slug}/{number}.min.json"
    out = {"slug": slug, "number": number, "ar": None, "en": None, "grade": None}

    for which, url in (("ar", url_ar), ("en", url_en)):
        try:
            req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
            with urllib.request.urlopen(req, timeout=20) as r:
                data = json.loads(r.read())
            h = data["hadiths"][0]
            text = h.get("text", "").strip()
            if which == "ar":
                out["ar"] = text
            else:
                out["en"] = text
                grades = h.get("grades") or []
                if grades:
                    out["grade"] = grades[0].get("grade", "")
        except Exception as e:
            print(f"  WARN {slug}/{number} ({which}): {e}", file=sys.stderr)

    if out["ar"] is None and out["en"] is None:
        return None
    return out


def main():
    print("Collecting hadith refs...", file=sys.stderr)
    refs, skipped = collect_refs()
    print(f"Found {len(refs)} unique refs across {len(set(s for s, _ in refs))} collections.", file=sys.stderr)
    if skipped:
        print(f"Skipped (no edition mapping): {skipped}", file=sys.stderr)

    print(f"Fetching {len(refs)} refs (12 concurrent)...", file=sys.stderr)
    result = {}
    errors = []
    with ThreadPoolExecutor(max_workers=12) as executor:
        futures = {executor.submit(fetch_one, s, n): (s, n) for s, n in refs}
        for i, future in enumerate(as_completed(futures), 1):
            slug, number = futures[future]
            data = future.result()
            key = f"{slug}:{number}"
            if data:
                result[key] = {
                    "collection": DISPLAY_MAP.get(slug, slug),
                    "number": number,
                    "ar": data["ar"] or "",
                    "en": data["en"] or "",
                    "grade": data["grade"] or "",
                }
            else:
                errors.append(key)
            if i % 25 == 0 or i == len(refs):
                print(f"  {i}/{len(refs)} done", file=sys.stderr)

    if errors:
        print(f"Failed refs ({len(errors)}): {errors[:20]}{'...' if len(errors) > 20 else ''}", file=sys.stderr)

    out_path = os.path.normpath(OUT_FILE)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by scripts/fetch-hadith.py — do not edit manually.\n")
        f.write("// Source: fawazahmed0/hadith-api (Arabic + English by collection:number).\n")
        f.write("export const hadithData = ")
        json.dump(result, f, ensure_ascii=False, separators=(",", ":"))
        f.write(";\n")

    print(f"Written {len(result)} hadiths to {out_path}", file=sys.stderr)


if __name__ == "__main__":
    main()
