"""
One-time script: fetch word-by-word + full translation for all Quran verses
cited in seed-task files, and write to src/data/quran-wbw.js.

Usage: python scripts/fetch-quran-wbw.py
"""
import urllib.request
import json
import sys
import os
import subprocess
from concurrent.futures import ThreadPoolExecutor, as_completed

BASE_URL = "https://api.quran.com/api/v4"
SEED_DIR = os.path.join(os.path.dirname(__file__), "..", "src", "data", "seed-tasks")
OUT_FILE = os.path.join(os.path.dirname(__file__), "..", "src", "data", "quran-wbw.js")

def grep_verse_refs():
    """Collect all unique verse refs from seed-task files using grep."""
    result = subprocess.run(
        ["grep", "-hro", "### Quran ([0-9]*:[0-9]*)", SEED_DIR],
        capture_output=True, text=True
    )
    refs = set()
    for line in result.stdout.splitlines():
        # extract e.g. "3:53" from "### Quran (3:53)"
        inner = line.strip().removeprefix("### Quran (").removesuffix(")")
        if ":" in inner:
            refs.add(inner)
    return sorted(refs)

def fetch_chapters():
    url = f"{BASE_URL}/chapters?language=en"
    req = urllib.request.Request(url, headers={"Accept": "application/json", "User-Agent": "Mozilla/5.0"})
    with urllib.request.urlopen(req, timeout=15) as r:
        data = json.loads(r.read())
    return {c["id"]: c["name_simple"] for c in data["chapters"]}

def fetch_verse(ref, chapter_names):
    url = (
        f"{BASE_URL}/verses/by_key/{ref}"
        f"?words=true&word_fields=text_uthmani,translation&translations=85"
    )
    req = urllib.request.Request(url, headers={"Accept": "application/json", "User-Agent": "Mozilla/5.0"})
    try:
        with urllib.request.urlopen(req, timeout=15) as r:
            data = json.loads(r.read())
    except Exception as e:
        print(f"  ERROR {ref}: {e}", file=sys.stderr)
        return ref, None

    v = data["verse"]
    words = [
        {"ar": w["text_uthmani"], "en": w["translation"]["text"]}
        for w in v["words"]
        if w.get("char_type_name") == "word"
    ]
    translation = ""
    if v.get("translations"):
        translation = v["translations"][0]["text"]
        # strip trailing unicode quotes quran.com sometimes adds
        translation = translation.strip("\u2018\u2019\u201c\u201d\u2032\u2033")

    surah_num, ayah_num = ref.split(":")
    return ref, {
        "surah": chapter_names.get(int(surah_num), ""),
        "surahNum": int(surah_num),
        "ayahNum": int(ayah_num),
        "words": words,
        "translation": translation,
    }

def main():
    print("Collecting verse references...", file=sys.stderr)
    refs = grep_verse_refs()
    print(f"Found {len(refs)} unique verse references.", file=sys.stderr)

    print("Fetching chapter names...", file=sys.stderr)
    chapter_names = fetch_chapters()

    print(f"Fetching {len(refs)} verses (10 concurrent)...", file=sys.stderr)
    result = {}
    errors = []
    with ThreadPoolExecutor(max_workers=10) as executor:
        futures = {executor.submit(fetch_verse, ref, chapter_names): ref for ref in refs}
        for i, future in enumerate(as_completed(futures), 1):
            ref, data = future.result()
            if data:
                result[ref] = data
            else:
                errors.append(ref)
            if i % 50 == 0 or i == len(refs):
                print(f"  {i}/{len(refs)} done", file=sys.stderr)

    if errors:
        print(f"Failed refs ({len(errors)}): {errors}", file=sys.stderr)

    out_path = os.path.normpath(OUT_FILE)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by scripts/fetch-quran-wbw.py — do not edit manually.\n")
        f.write("// Word-by-word + translation data from quran.com API (translations=85, Khattab).\n")
        f.write("export const quranWBW = ")
        json.dump(result, f, ensure_ascii=False, separators=(",", ":"))
        f.write(";\n")

    print(f"Written {len(result)} verses to {out_path}", file=sys.stderr)
    if errors:
        sys.exit(1)

if __name__ == "__main__":
    main()
